/*
 * Copyright 2026 杭州开云集致科技有限公司
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'com.clougence.java-conventions'
    id 'antlr'
}

dependencies {
    antlr "org.antlr:antlr4:${ANTLR_VERSION}"
    api "org.antlr:antlr4-runtime:${ANTLR_VERSION}"
    api project(':cg-dslparser')
    api project(':sqlc-common')
}

description = 'sql-iso-sql92'

tasks.named('generateGrammarSource') {
    arguments += ['-visitor', '-package', 'com.clougence.sql.iso.sql92.parser.antlr']
}
