export const cicdApi = {
  dmCicdFlowList: '/api/entry/cicd/flow/list',
  dmCicdDevopsUsers: '/api/entry/cicd/flow/users',
  dmCicdCreate: '/api/entry/cicd/flow/create',
  dmCicdBatchCreate: '/api/entry/cicd/flow/batchCreate',
  dmCicdDevopsScmList: '/api/entry/cicd/flow/gitOpsScmList',
  dmCicdDevopsRepos: '/api/entry/cicd/flow/gitOpsRepos',
  dmCicdDevopsDsInsLevels: '/api/entry/cicd/flow/dsInsLevels',
  dmCicdDevopsDsDbLevels: '/api/entry/cicd/flow/dsDbLevels',

  dmCicdFlowDetail: '/api/entry/cicd/flow/detail',
  dmCicdFlowParentCandidates: '/api/entry/cicd/flow/parentCandidates',
  dmCicdFlowParentConfig: '/api/entry/cicd/flow/parentConfig',
  dmCicdFlowUpdate: '/api/entry/cicd/flow/update',
  dmCicdFlowDevopsList: '/api/entry/cicd/flow/gitOpsList',
  dmCicdFlowFetchImConfig: '/api/entry/cicd/flow/fetchImConfig',
  dmCicdFlowPushImConfig: '/api/entry/cicd/flow/pushImConfig',
  dmCicdFlowDevopsCreate: '/api/entry/cicd/flow/gitOpsCreate',
  dmCicdFlowDevopsDelete: '/api/entry/cicd/flow/gitOpsDelete',
  dmCicdFlowDevopsSwitch: '/api/entry/cicd/flow/switch',
  dmCicdFlowArchive: '/api/entry/cicd/flow/archive',
  dmCicdFlowRecover: '/api/entry/cicd/flow/recover',
  dmCicdFlowDelete: '/api/entry/cicd/flow/delete',
  dmCicdFlowTriggerChange: '/api/entry/cicd/flow/triggerChange',
  dmCicdFlowTriggerSnapshot: '/api/entry/cicd/flow/triggerSnapshot',
  dmCicdFlowTriggerConfig: '/api/entry/cicd/flow/triggerConfig',
  dmCicdFlowCallBackConfig: '/api/entry/cicd/flow/callbackConfig',

  dmCicdChangeList: '/api/entry/cicd/change/changeList',
  dmCicdChangeDetail: '/api/entry/cicd/change/changeDetail',
  dmCicdChangeSqlPreview: '/api/entry/cicd/change/changeSqlPreview'
};
