/*
 * Copyright 2026 杭州开云集致科技有限公司
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

lexer grammar DmSqlLexer;

channels { COMMENTS }

SELECT       : S E L E C T;
SQL_CALC_FOUND_ROWS : S Q L '_' C A L C '_' F O U N D '_' R O W S;
WITH         : W I T H;
WINDOW       : W I N D O W;
RECURSIVE    : R E C U R S I V E;
REF          : R E F;
INSERT       : I N S E R T;
INTO         : I N T O;
VALUES       : V A L U E S;
VALUE        : V A L U E;
JSON_VALUE   : J S O N '_' V A L U E;
JSON_QUERY   : J S O N '_' Q U E R Y;
JSON_TABLE   : J S O N '_' T A B L E;
JSON_ARRAY   : J S O N '_' A R R A Y;
JSON_OBJECT  : J S O N '_' O B J E C T;
JSON_OVERLAPS : J S O N '_' O V E R L A P S;
JSON_SET    : J S O N '_' S E T;
JSON_REPLACE : J S O N '_' R E P L A C E;
JSON_INSERT : J S O N '_' I N S E R T;
JSON_EXTRACT : J S O N '_' E X T R A C T;
JSON_UNQUOTE : J S O N '_' U N Q U O T E;
JSON_KEYS   : J S O N '_' K E Y S;
JSON_CONTAINS_PATH : J S O N '_' C O N T A I N S '_' P A T H;
JSON_BUILD_ARRAY : J S O N '_' B U I L D '_' A R R A Y;
JSON_BUILD_OBJECT : J S O N '_' B U I L D '_' O B J E C T;
JSON_TYPE   : J S O N '_' T Y P E;
JSON_TYPEOF : J S O N '_' T Y P E O F;
JSON_CONCAT : J S O N '_' C O N C A T;
JSON_VALID  : J S O N '_' V A L I D;
JSON_OBJECT_KEYS : J S O N '_' O B J E C T '_' K E Y S;
ROW_TO_JSON : R O W '_' T O '_' J S O N;
TO_JSONB    : T O '_' J S O N B;
TO_JSON     : T O '_' J S O N;
JSONB_OBJECT_KEYS : J S O N B '_' O B J E C T '_' K E Y S;
JSONB_EACH   : J S O N B '_' E A C H;
JSONB_EACH_TEXT : J S O N B '_' E A C H '_' T E X T;
JSONB_ARRAY_ELEMENTS : J S O N B '_' A R R A Y '_' E L E M E N T S;
JSONB_ARRAY_ELEMENTS_TEXT : J S O N B '_' A R R A Y '_' E L E M E N T S '_' T E X T;
JSONB_STRIP_NULLS : J S O N B '_' S T R I P '_' N U L L S;
JSONB_SET   : J S O N B '_' S E T;
JSONB_OBJECT_AGG : J S O N B '_' O B J E C T '_' A G G;
JSONB_CONCAT : J S O N B '_' C O N C A T;
JSONB_BUILD_OBJECT : J S O N B '_' B U I L D '_' O B J E C T;
JSONB_AGG   : J S O N B '_' A G G;
JSONB_BUILD_ARRAY : J S O N B '_' B U I L D '_' A R R A Y;
JSONB_TYPEOF : J S O N B '_' T Y P E O F;
JSON         : J S O N;
UPDATE       : U P D A T E;
SET          : S E T;
DELETE       : D E L E T E;
FROM         : F R O M;
WHERE        : W H E R E;
MERGE        : M E R G E;
USING        : U S I N G;
MATCHED      : M A T C H E D;
DDL          : D D L;
AUDIT        : A U D I T;
NOAUDIT      : N O A U D I T;
LOGIN        : L O G I N;
LOGON        : L O G O N;
LOGOUT       : L O G O U T;
LOGOFF       : L O G O F F;
SERERR       : S E R E R R;
TIMER        : T I M E R;
ONCE         : O N C E;
STARTUP      : S T A R T U P;
SHUTDOWN     : S H U T D O W N;
FLASHBACK    : F L A S H B A C K;
BACKUP       : B A C K U P;
RESTORE      : R E S T O R E;
RECOVER      : R E C O V E R;
REMOVE       : R E M O V E;
REPAIR       : R E P A I R;
CONFIGURE    : C O N F I G U R E;
LOAD         : L O A D;
CHECKPOINT   : C H E C K P O I N T;
BACKUPSET    : B A C K U P S E T;
BACKUPSETS   : B A C K U P S E T S;
BACKUPNAME   : B A C K U P N A M E;
BACKUPINFO   : B A C K U P I N F O;
INFO         : I N F O;
META         : M E T A;
TXT          : T X T;
DB           : D B;
BACKUPDIR    : B A C K U P D I R;
BACKED       : B A C K E D;
UP           : U P;
SINCE        : S I N C E;
BASE         : B A S E;
ARCHIVEDIR   : A R C H I V E D I R;
ARCHIVELOG   : A R C H I V E L O G;
NOARCHIVELOG : N O A R C H I V E L O G;
ARCHIVE      : A R C H I V E;
LOGFILE      : L O G F I L E;
MOUNT        : M O U N T;
SUSPEND      : S U S P E N D;
STANDBY      : S T A N D B Y;
DEVICE       : D E V I C E;
DISK         : D I S K;
TAPE         : T A P E;
MAXPIECESIZE : M A X P I E C E S I Z E;
COMPRESSED   : C O M P R E S S E D;
TRACE        : T R A C E;
FILE         : F I L E;
FILES        : F I L E S;
TASK         : T A S K;
THREAD       : T H R E A D;
MAPPED       : M A P P E D;
USE          : U S E;
DB_MAGIC     : D B '_' M A G I C;
BAK_MAGIC    : B A K '_' M A G I C;
END_LSN      : E N D '_' L S N;
REUSE_DMINI  : R E U S E '_' D M I N I;
DMINI        : D M I N I;
SHADOW       : S H A D O W;
DDL_CLONE    : D D L '_' C L O N E;
CUMULATIVE   : C U M U L A T I V E;
STRUCT       : S T R U C T;
TRXID        : T R X I D;
TIMES        : T I M E S;
INPUT        : I N P U T;
SPACE        : S P A C E;
OVERWRITE    : O V E R W R I T E;
EXTEND       : E X T E N D;
CLEAR        : C L E A R;
AUTO_CLEAR   : A U T O '_' C L E A R;
SPEED        : S P E E D;
NODE         : N O D E;
STAT         : S T A T;
CREATE       : C R E A T E;
OR           : O R;
REPLACE      : R E P L A C E;
FORCE        : F O R C E;
GLOBAL       : G L O B A L;
LOCAL        : L O C A L;
TEMPORARY    : T E M P O R A R Y;
TABLE        : T A B L E;
VIEW         : V I E W;
MATERIALIZED : M A T E R I A L I Z E D;
INDEX        : I N D E X;
CLUSTER      : C L U S T E R;
PARTIAL      : P A R T I A L;
BITMAP       : B I T M A P;
SPATIAL      : S P A T I A L;
ARRAY        : A R R A Y;
UNIQUE       : U N I Q U E;
SCHEMA       : S C H E M A;
DATABASE     : D A T A B A S E;
TABLESPACE   : T A B L E S P A C E;
SEQUENCE     : S E Q U E N C E;
USER         : U S E R;
ROLE         : R O L E;
PROCEDURE    : P R O C E D U R E;
FUNCTION     : F U N C T I O N;
CALCULATE    : C A L C U L A T E;
TRIGGER      : T R I G G E R;
BEFORE       : B E F O R E;
AFTER        : A F T E R;
INSTEAD      : I N S T E A D;
REFERENCING  : R E F E R E N C I N G;
SYNONYM      : S Y N O N Y M;
TYPE         : T Y P E;
UNDER        : U N D E R;
FINAL        : F I N A L;
VARRAY       : V A R R A Y;
NEW          : N E W;
MEMBER       : M E M B E R;
MULTISET     : M U L T I S E T;
STATIC       : S T A T I C;
CONSTRUCTOR  : C O N S T R U C T O R;
INSTANTIABLE : I N S T A N T I A B L E;
PERSISTABLE  : P E R S I S T A B L E;
OVERRIDING   : O V E R R I D I N G;
MAP          : M A P;
PACKAGE      : P A C K A G E;
BODY         : B O D Y;
DIRECTORY    : D I R E C T O R Y;
LIBRARY      : L I B R A R Y;
CONTEXT      : C O N T E X T;
DOMAIN       : D O M A I N;
PROFILE      : P R O F I L E;
LINK         : L I N K;
PUBLIC       : P U B L I C;
PRIVATE      : P R I V A T E;
ALTER        : A L T E R;
DROP         : D R O P;
TRUNCATE     : T R U N C A T E;
COMMENT      : C O M M E N T;
ON           : O N;
OF           : O F;
COLUMN       : C O L U M N;
COLUMNS      : C O L U M N S;
IS           : I S;
NULL_LITERAL : N U L L;
IF           : I F;
EXISTS       : E X I S T S;
NOT          : N O T;
AS           : A S;
DEFAULT      : D E F A U L T;
PRIMARY      : P R I M A R Y;
KEY          : K E Y;
FOREIGN      : F O R E I G N;
REFERENCES   : R E F E R E N C E S;
CONSTRAINT   : C O N S T R A I N T;
CHECK        : C H E C K;
ADD          : A D D;
MODIFY       : M O D I F Y;
RENAME       : R E N A M E;
TO           : T O;
CASCADE      : C A S C A D E;
CASCADED     : C A S C A D E D;
RESTRICT     : R E S T R I C T;
STRICT       : S T R I C T;
LAX          : L A X;
BY           : B Y;
ORDER        : O R D E R;
GROUP        : G R O U P;
HAVING       : H A V I N G;
ROLLUP       : R O L L U P;
CUBE         : C U B E;
GROUPING     : G R O U P I N G;
SETS         : S E T S;
AGGREGATE    : A G G R E G A T E;
LEFTARG      : L E F T A R G;
RIGHTARG     : R I G H T A R G;
UNION        : U N I O N;
INTERSECT    : I N T E R S E C T;
MINUS_SET    : M I N U S;
EXCEPT       : E X C E P T;
WITHIN       : W I T H I N;
OVER         : O V E R;
OPERATOR     : O P E R A T O R;
OVERLAPS     : O V E R L A P S;
OVERFLOW     : O V E R F L O W;
PARTITION    : P A R T I T I O N;
SUBPARTITION : S U B P A R T I T I O N;
PARTITIONS   : P A R T I T I O N S;
SUBPARTITIONS : S U B P A R T I T I O N S;
MODEL        : M O D E L;
DIMENSION    : D I M E N S I O N;
MEASURES     : M E A S U R E S;
RULES        : R U L E S;
UPSERT       : U P S E R T;
NAV          : N A V;
UPDATED      : U P D A T E D;
ITERATE      : I T E R A T E;
AUTOMATIC    : A U T O M A T I C;
SEQUENTIAL   : S E Q U E N T I A L;
REFERENCE    : R E F E R E N C E;
HASH         : H A S H;
LIST         : L I S T;
EQU          : E Q U;
LESS         : L E S S;
THAN         : T H A N;
NOMAXVALUE   : N O M A X V A L U E;
NOMINVALUE   : N O M I N V A L U E;
MAXVALUE     : M A X V A L U E;
MINVALUE     : M I N V A L U E;
CYCLE        : C Y C L E;
SEARCH       : S E A R C H;
BREADTH      : B R E A D T H;
DEPTH        : D E P T H;
TEMPLATE     : T E M P L A T E;
STORAGE      : S T O R A G E;
STORE        : S T O R E;
HASHPARTMAP  : H A S H P A R T M A P;
DISTRIBUTED  : D I S T R I B U T E D;
FULLY        : F U L L Y;
MAIN         : M A I N;
PIVOT        : P I V O T;
UNPIVOT      : U N P I V O T;
INCLUDE      : I N C L U D E;
EXCLUDE      : E X C L U D E;
XMLTABLE     : X M L T A B L E;
XMLNAMESPACES : X M L N A M E S P A C E S;
XMLNAMESPACE : X M L N A M E S P A C E;
XMLAGG       : X M L A G G;
XMLELEMENT   : X M L E L E M E N T;
XMLATTRIBUTES : X M L A T T R I B U T E S;
XMLFOREST    : X M L F O R E S T;
XMLCAST      : X M L C A S T;
XMLPARSE     : X M L P A R S E;
XMLQUERY     : X M L Q U E R Y;
XMLSERIALIZE : X M L S E R I A L I Z E;
XMLTYPE      : X M L T Y P E;
SF_XMLQUERY  : S F '_' X M L Q U E R Y;
EXISTSNODE   : E X I S T S N O D E;
EXTRACTVALUE : E X T R A C T V A L U E;
XMLSEQUENCE  : X M L S E Q U E N C E;
DELETEXML    : D E L E T E X M L;
APPENDCHILDXML : A P P E N D C H I L D X M L;
INSERTCHILDXML : I N S E R T C H I L D X M L;
INSERTCHILDXMLAFTER : I N S E R T C H I L D X M L A F T E R;
INSERTCHILDXMLBEFORE : I N S E R T C H I L D X M L B E F O R E;
INSERTXMLBEFORE : I N S E R T X M L B E F O R E;
INSERTXMLAFTER : I N S E R T X M L A F T E R;
UPDATEXML    : U P D A T E X M L;
XMLTRANSFORM : X M L T R A N S F O R M;
XML          : X M L;
EVALNAME     : E V A L N A M E;
CONTENT      : C O N T E N T;
DOCUMENT     : D O C U M E N T;
WELLFORMED   : W E L L F O R M E D;
ENCODING     : E N C O D I N G;
VERSION      : V E R S I O N;
INDENT       : I N D E N T;
HIDE         : H I D E;
SHOW         : S H O W;
DEFAULTS     : D E F A U L T S;
PASSING      : P A S S I N G;
SAMPLE       : S A M P L E;
SEED         : S E E D;
BLOCK        : B L O C K;
ALL          : A L L;
ANY          : A N Y;
SOME         : S O M E;
DISTINCT     : D I S T I N C T;
CORRESPONDING : C O R R E S P O N D I N G;
JOIN         : J O I N;
INNER        : I N N E R;
LEFT         : L E F T;
RIGHT        : R I G H T;
FULL         : F U L L;
OUT          : O U T;
OUTER        : O U T E R;
CROSS        : C R O S S;
APPLY        : A P P L Y;
NATURAL      : N A T U R A L;
CASE         : C A S E;
WHEN         : W H E N;
THEN         : T H E N;
ELSE         : E L S E;
ELSIF        : E L S I F;
ELSEIF       : E L S E I F;
END          : E N D;
AND          : A N D;
CONTAINS     : C O N T A I N S;
LIKE         : L I K E;
ESCAPE       : E S C A P E;
IN           : I N;
BETWEEN      : B E T W E E N;
CONNECT      : C O N N E C T;
NOCYCLE      : N O C Y C L E;
PRIOR        : P R I O R;
CONNECT_BY_ROOT : C O N N E C T '_' B Y '_' R O O T;
CONNECT_BY_ISLEAF : C O N N E C T '_' B Y '_' I S L E A F;
CONNECT_BY_ISCYCLE : C O N N E C T '_' B Y '_' I S C Y C L E;
SYS_CONNECT_BY_PATH : S Y S '_' C O N N E C T '_' B Y '_' P A T H;
ASC          : A S C;
DESC         : D E S C;
SIBLINGS     : S I B L I N G S;
COLLATE      : C O L L A T E;
NOCACHE      : N O C A C H E;
NOORDER      : N O O R D E R;
CACHE        : C A C H E;
LIMIT        : L I M I T;
OFFSET       : O F F S E T;
FETCH        : F E T C H;
ABSOLUTE     : A B S O L U T E;
RELATIVE     : R E L A T I V E;
FIRST        : F I R S T;
LAST         : L A S T;
NEXT         : N E X T;
ROWS         : R O W S;
ROW          : R O W;
EACH         : E A C H;
STATEMENT    : S T A T E M E N T;
FOLLOWS      : F O L L O W S;
PRECEDES     : P R E C E D E S;
MOVEMENT     : M O V E M E N T;
RANGE        : R A N G E;
BINARY       : B I N A R Y;
UNBOUNDED    : U N B O U N D E D;
PRECEDING    : P R E C E D I N G;
FOLLOWING    : F O L L O W I N G;
CURRENT      : C U R R E N T;
ONLY         : O N L Y;
TIES         : T I E S;
PERCENT_KEYWORD : P E R C E N T;
TOP          : T O P;
IDENTITY     : I D E N T I T Y;
IDENTITY_INSERT : I D E N T I T Y '_' I N S E R T;
AUTO         : A U T O;
AUTO_INCREMENT : A U T O '_'? I N C R E M E N T;
START        : S T A R T;
INCREMENT    : I N C R E M E N T;
DATAFILE     : D A T A F I L E;
LOCATION     : L O C A T I O N;
PARMS        : P A R M S;
FIELDS       : F I E L D S;
RECORD       : R E C O R D;
RECORDS      : R E C O R D S;
DELIMITED    : D E L I M I T E D;
SIZE         : S I Z E;
MIRROR       : M I R R O R;
AUTOEXTEND   : A U T O E X T E N D;
MAXSIZE      : M A X S I Z E;
WRAPPED      : W R A P P E D;
STRIPING     : S T R I P I N G;
HIGH         : H I G H;
NORMAL       : N O R M A L;
EXTERNAL     : E X T E R N A L;
HUGE         : H U G E;
COMPRESS     : C O M P R E S S;
PATH         : P A T H;
FORMAT       : F O R M A T;
NESTED       : N E S T E D;
ORDINALITY   : O R D I N A L I T Y;
OPTIMIZE     : O P T I M I Z E;
COPY         : C O P Y;
LANGUAGE     : L A N G U A G E;
NAME         : N A M E;
C_LANGUAGE   : C;
CS_LANGUAGE  : C S;
JAVA_LANGUAGE : J A V A;
MICRO        : M I C R O;
ONLINE       : O N L I N E;
OFFLINE      : O F F L I N E;
OFF          : O F F;
BUILD        : B U I L D;
DEFERRED     : D E F E R R E D;
MEMORY       : M E M O R Y;
SPFILE       : S P F I L E;
PREBUILT     : P R E B U I L T;
REDUCED      : R E D U C E D;
PRECISION    : P R E C I S I O N;
DOUBLE       : D O U B L E;
CHAR         : C H A R;
CHARACTER    : C H A R A C T E R;
NCHAR        : N C H A R;
NATIONAL     : N A T I O N A L;
LARGE        : L A R G E;
BYTE         : B Y T E;
VARYING      : V A R Y I N G;
NEVER        : N E V E R;
REFRESH      : R E F R E S H;
FAST         : F A S T;
COMPLETE     : C O M P L E T E;
DEMAND       : D E M A N D;
QUERY        : Q U E R Y;
REWRITE      : R E W R I T E;
PURGE        : P U R G E;
REBUILD      : R E B U I L D;
MOVE         : M O V E;
REUSE        : R E U S E;
SPLIT        : S P L I T;
EXCHANGE     : E X C H A N G E;
INDEXES      : I N D E X E S;
AT_KEYWORD   : A T;
SECTION      : S E C T I O N;
FILESIZE     : F I L E S I Z E;
DELTA        : D E L T A;
SYNCHRONOUS  : S Y N C H R O N O U S;
ASYNCHRONOUS : A S Y N C H R O N O U S;
NONE         : N O N E;
ROWID        : R O W I D;
ROWNUM       : R O W N U M;
WITHOUT      : W I T H O U T;
KEYS         : K E Y S;
NOSORT       : N O S O R T;
UNUSABLE     : U N U S A B L E;
PARALLEL     : P A R A L L E L;
NOPARALLEL   : N O P A R A L L E L;
RANDOMLY     : R A N D O M L Y;
PENDANT      : P E N D A N T;
MATCH        : M A T C H;
SIMPLE       : S I M P L E;
ACTION       : A C T I O N;
VISIBLE      : V I S I B L E;
INVISIBLE    : I N V I S I B L E;
VIRTUAL      : V I R T U A L;
GENERATED    : G E N E R A T E D;
ALWAYS       : A L W A Y S;
VALIDATE     : V A L I D A T E;
NOVALIDATE   : N O V A L I D A T E;
BRANCH       : B R A N C H;
NOBRANCH     : N O B R A N C H;
CLUSTERBTR   : C L U S T E R B T R;
COUNTER      : C O U N T E R;
COUNT        : C O U N T;
LONG         : L O N G;
FILLFACTOR   : F I L L F A C T O R;
MINEXTENTS   : M I N E X T E N T S;
INITIAL      : I N I T I A L;
DISKSPACE    : D I S K S P A C E;
SEGMENT      : S E G M E N T;
CREATION     : C R E A T I O N;
ADVANCED     : A D V A N C E D;
LOGIC        : L O G I C;
LOG          : L O G;
CORRUPT      : C O R R U P T;
RESIZE       : R E S I Z E;
COMPILE      : C O M P I L E;
DEBUG        : D E B U G;
AUTHID       : A U T H I D;
AUTHORIZATION : A U T H O R I Z A T I O N;
DEFINER      : D E F I N E R;
CURRENT_USER : C U R R E N T '_' U S E R;
ENCRYPTION   : E N C R Y P T I O N;
CURSOR       : C U R S O R;
SYS_REFCURSOR : S Y S '_' R E F C U R S O R;
FOUND        : F O U N D;
NOTFOUND     : N O T F O U N D;
ISOPEN       : I S O P E N;
ROWCOUNT     : R O W C O U N T;
BULK_ROWCOUNT : B U L K '_' R O W C O U N T;
BULK_EXCEPTIONS : B U L K '_' E X C E P T I O N S;
CONSTANT     : C O N S T A N T;
ROWTYPE      : R O W T Y P E;
SUBTYPE      : S U B T Y P E;
PRAGMA       : P R A G M A;
EXCEPTION    : E X C E P T I O N;
TRY          : T R Y;
CATCH        : C A T C H;
THROW        : T H R O W;
SWITCH       : S W I T C H;
BREAK        : B R E A K;
LOOP         : L O O P;
WHILE        : W H I L E;
REPEAT       : R E P E A T;
UNTIL        : U N T I L;
FORALL       : F O R A L L;
INDICES      : I N D I C E S;
GOTO         : G O T O;
EXIT         : E X I T;
CONTINUE     : C O N T I N U E;
REVERSE      : R E V E R S E;
RAISE        : R A I S E;
OPEN         : O P E N;
CLOSE        : C L O S E;
IMMEDIATE    : I M M E D I A T E;
BATCH        : B A T C H;
DEFERRABLE   : D E F E R R A B L E;
INITIALLY    : I N I T I A L L Y;
SAVE         : S A V E;
EXCEPTIONS   : E X C E P T I O N S;
RETURN       : R E T U R N;
RETURNING    : R E T U R N I N G;
PRINT        : P R I N T;
BULK         : B U L K;
COLLECT      : C O L L E C T;
RESULT_CACHE : R E S U L T '_' C A C H E;
DETERMINISTIC : D E T E R M I N I S T I C;
PARALLEL_ENABLE : P A R A L L E L '_' E N A B L E;
PIPE         : P I P E;
PIPELINED    : P I P E L I N E D;
IDENTIFIED   : I D E N T I F I E D;
PASSWORD_POLICY : P A S S W O R D '_' P O L I C Y;
PASSWORD     : P A S S W O R D;
ACCOUNT      : A C C O U N T;
UNLOCK       : U N L O C K;
ENCRYPT      : E N C R Y P T;
MANUAL       : M A N U A L;
INITIALIZED  : I N I T I A L I Z E D;
EXTERNALLY   : E X T E R N A L L Y;
ACCESSED     : A C C E S S E D;
GLOBALLY     : G L O B A L L Y;
RADIUS       : R A D I U S;
NO           : N O;
SALT         : S A L T;
SESSION_PER_USER : S E S S I O N '_' P E R '_' U S E R;
CONNECT_IDLE_TIME : C O N N E C T '_' I D L E '_' T I M E;
CONNECT_TIME : C O N N E C T '_' T I M E;
CPU_PER_CALL : C P U '_' P E R '_' C A L L;
CPU_PER_SESSION : C P U '_' P E R '_' S E S S I O N;
MEM_SPACE    : M E M '_' S P A C E;
READ_PER_CALL : R E A D '_' P E R '_' C A L L;
READ_PER_SESSION : R E A D '_' P E R '_' S E S S I O N;
FAILED_LOGIN_ATTEMPTS : F A I L E D '_' L O G I N '_' A T T E M P T S;
PASSWORD_LIFE_TIME : P A S S W O R D '_' L I F E '_' T I M E;
PASSWORD_REUSE_TIME : P A S S W O R D '_' R E U S E '_' T I M E;
PASSWORD_REUSE_MAX : P A S S W O R D '_' R E U S E '_' M A X;
PASSWORD_LOCK_TIME : P A S S W O R D '_' L O C K '_' T I M E;
PASSWORD_GRACE_TIME : P A S S W O R D '_' G R A C E '_' T I M E;
INACTIVE_ACCOUNT_TIME : I N A C T I V E '_' A C C O U N T '_' T I M E;
GLOBAL_SESSION_PER_USER : G L O B A L '_' S E S S I O N '_' P E R '_' U S E R;
ALLOW_IP     : A L L O W '_' I P;
NOT_ALLOW_IP : N O T '_' A L L O W '_' I P;
ALLOW_DATETIME : A L L O W '_' D A T E T I M E;
NOT_ALLOW_DATETIME : N O T '_' A L L O W '_' D A T E T I M E;
RETAIN       : R E T A I N;
DISCARD      : D I S C A R D;
OLD          : O L D;
MON          : M O N;
TUE          : T U E;
WED          : W E D;
THU          : T H U;
THUR         : T H U R;
THURS        : T H U R S;
FRI          : F R I;
SAT          : S A T;
SUN          : S U N;
EXPIRE       : E X P I R E;
QUOTA        : Q U O T A;
UNLIMITED    : U N L I M I T E D;
CAST         : C A S T;
EXTRACT      : E X T R A C T;
TRIM         : T R I M;
SUBSTRING    : S U B S T R I N G;
TREAT        : T R E A T;
TRANSLATE    : T R A N S L A T E;
ASCII        : A S C I I;
PRETTY       : P R E T T Y;
WRAPPER      : W R A P P E R;
CONDITIONAL  : C O N D I T I O N A L;
UNCONDITIONAL : U N C O N D I T I O N A L;
EMPTY        : E M P T Y;
ERROR        : E R R O R;
ERRORS       : E R R O R S;
REJECT       : R E J E C T;
OBJECT       : O B J E C T;
TRUE         : T R U E;
FALSE        : F A L S E;
LEADING      : L E A D I N G;
TRAILING     : T R A I L I N G;
BOTH         : B O T H;
POSITION     : P O S I T I O N;
OVERLAY      : O V E R L A Y;
PLACING      : P L A C I N G;
DATE         : D A T E;
TIME         : T I M E;
ZONE         : Z O N E;
DATETIME     : D A T E T I M E;
TIMESTAMP    : T I M E S T A M P;
INTERVAL     : I N T E R V A L;
YEAR         : Y E A R;
MONTH        : M O N T H;
DAY          : D A Y;
HOUR         : H O U R;
MINUTE       : M I N U T E;
SECOND       : S E C O N D;
TIMEZONE_HOUR : T I M E Z O N E '_' H O U R;
TIMEZONE_MINUTE : T I M E Z O N E '_' M I N U T E;
WEEK         : W E E K;
SCN          : S C N;
LSN          : L S N;
VERSIONS     : V E R S I O N S;
ENABLE       : E N A B L E;
DISABLE      : D I S A B L E;
TRIGGERS     : T R I G G E R S;
WAIT         : W A I T;
NOWAIT       : N O W A I T;
READ         : R E A D;
WRITE        : W R I T E;
LOCK         : L O C K;
MODE         : M O D E;
INTENT       : I N T E N T;
PRESERVE     : P R E S E R V E;
SHARE        : S H A R E;
EXCLUSIVE    : E X C L U S I V E;
DUMP         : D U M P;
DML          : D M L;
MONITORING   : M O N I T O R I N G;
NOMONITORING : N O M O N I T O R I N G;
USAGE        : U S A G E;
PRIVILEGES   : P R I V I L E G E S;
ADMIN        : A D M I N;
OPTION       : O P T I O N;
CLASS        : C L A S S;
ABSTRACT     : A B S T R A C T;
EXTENDS      : E X T E N D S;
OVERRIDE     : O V E R R I D E;
SKIP_KEYWORD : S K I P;
LOCKED       : L O C K E D;
KEEP         : K E E P;
DENSE_RANK   : D E N S E '_' R A N K;
NULLS        : N U L L S;
RESPECT      : R E S P E C T;
IGNORE       : I G N O R E;
GRANT        : G R A N T;
REVOKE       : R E V O K E;
CALL         : C A L L;
EXEC         : E X E C;
EXECUTE      : E X E C U T E;
SP_SET_PARA_VALUE : S P '_' S E T '_' P A R A '_' V A L U E;
SP_SET_PARA_DOUBLE_VALUE : S P '_' S E T '_' P A R A '_' D O U B L E '_' V A L U E;
SP_SET_PARA_STRING_VALUE : S P '_' S E T '_' P A R A '_' S T R I N G '_' V A L U E;
SF_SET_SESSION_PARA_VALUE : S F '_' S E T '_' S E S S I O N '_' P A R A '_' V A L U E;
SP_RESET_SESSION_PARA_VALUE : S P '_' R E S E T '_' S E S S I O N '_' P A R A '_' V A L U E;
SP_SET_PARAM_IN_SESSION : S P '_' S E T '_' P A R A M '_' I N '_' S E S S I O N;
SF_SET_SYSTEM_PARA_VALUE : S F '_' S E T '_' S Y S T E M '_' P A R A '_' V A L U E;
SP_SET_INI_PARA_VALUE : S P '_' S E T '_' I N I '_' P A R A '_' V A L U E;
SP_SET_SESSION_READONLY : S P '_' S E T '_' S E S S I O N '_' R E A D O N L Y;
SP_SET_OGUID : S P '_' S E T '_' O G U I D;
SP_APPLY_KEEP_PKG : S P '_' A P P L Y '_' K E E P '_' P K G;
SP_CLEAR_ARCH_SEND_INFO : S P '_' C L E A R '_' A R C H '_' S E N D '_' I N F O;
SP_CLEAR_RAPPLY_STAT : S P '_' C L E A R '_' R A P P L Y '_' S T A T;
SP_TAB_INDEX_STAT_INIT : S P '_' T A B '_' I N D E X '_' S T A T '_' I N I T;
SP_DB_STAT_INIT : S P '_' D B '_' S T A T '_' I N I T;
SP_INDEX_STAT_INIT : S P '_' I N D E X '_' S T A T '_' I N I T;
SP_COL_STAT_INIT : S P '_' C O L '_' S T A T '_' I N I T;
SP_TAB_COL_STAT_INIT : S P '_' T A B '_' C O L '_' S T A T '_' I N I T;
SP_STAT_ON_TABLE_COLS : S P '_' S T A T '_' O N '_' T A B L E '_' C O L S;
SP_TAB_STAT_INIT : S P '_' T A B '_' S T A T '_' I N I T;
SP_SQL_STAT_INIT : S P '_' S Q L '_' S T A T '_' I N I T;
SP_INDEX_STAT_DEINIT : S P '_' I N D E X '_' S T A T '_' D E I N I T;
SP_COL_STAT_DEINIT : S P '_' C O L '_' S T A T '_' D E I N I T;
SP_TAB_COL_STAT_DEINIT : S P '_' T A B '_' C O L '_' S T A T '_' D E I N I T;
SP_TAB_STAT_DEINIT : S P '_' T A B '_' S T A T '_' D E I N I T;
SP_UPDATE_SYSSTATS : S P '_' U P D A T E '_' S Y S S T A T S;
SP_TAB_MSTAT_DEINIT : S P '_' T A B '_' M S T A T '_' D E I N I T;
SP_CREATE_AUTO_STAT_TRIGGER : S P '_' C R E A T E '_' A U T O '_' S T A T '_' T R I G G E R;
SP_FLUSH_MODIFICATIONS_INFO : S P '_' F L U S H '_' M O D I F I C A T I O N S '_' I N F O;
SP_CLEAN_MODIFICATIONS : S P '_' C L E A N '_' M O D I F I C A T I O N S;
SP_SET_ENABLE_AUDIT : S P '_' S E T '_' E N A B L E '_' A U D I T;
SP_AUDIT_STMT : S P '_' A U D I T '_' S T M T;
SP_NOAUDIT_STMT : S P '_' N O A U D I T '_' S T M T;
SP_AUDIT_OBJECT : S P '_' A U D I T '_' O B J E C T;
SP_NOAUDIT_OBJECT : S P '_' N O A U D I T '_' O B J E C T;
SP_AUDIT_SQLSEQ_START : S P '_' A U D I T '_' S Q L S E Q '_' S T A R T;
SP_AUDIT_SQLSEQ_ADD : S P '_' A U D I T '_' S Q L S E Q '_' A D D;
SP_AUDIT_SQLSEQ_END : S P '_' A U D I T '_' S Q L S E Q '_' E N D;
SP_AUDIT_SQLSEQ_DEL : S P '_' A U D I T '_' S Q L S E Q '_' D E L;
SP_AUDIT_SET_ENC : S P '_' A U D I T '_' S E T '_' E N C;
SP_DROP_AUDIT_FILE : S P '_' D R O P '_' A U D I T '_' F I L E;
SP_SWITCH_AUDIT_FILE : S P '_' S W I T C H '_' A U D I T '_' F I L E;
SP_CREATE_AUDIT_RULE : S P '_' C R E A T E '_' A U D I T '_' R U L E;
SP_DROP_AUDIT_RULE : S P '_' D R O P '_' A U D I T '_' R U L E;
SP_SET_ROLE : S P '_' S E T '_' R O L E;
SP_INIT_SVI_SYS : S P '_' I N I T '_' S V I '_' S Y S;
SP_SWITCH_SVI : S P '_' S W I T C H '_' S V I;
SP_RESTRICT_DBA : S P '_' R E S T R I C T '_' D B A;
BEGIN        : B E G I N;
DECLARE      : D E C L A R E;
LEXER        : L E X E R;
SYNC         : S Y N C;
TRANSACTION  : T R A N S A C T I O N;
TRX          : T R X;
SAVEPOINT    : S A V E P O I N T;
RELEASE      : R E L E A S E;
WORK         : W O R K;
ISOLATION    : I S O L A T I O N;
LEVEL        : L E V E L;
COMMITTED    : C O M M I T T E D;
UNCOMMITTED  : U N C O M M I T T E D;
SERIALIZABLE : S E R I A L I Z A B L E;
AUTOCOMMIT   : A U T O C O M M I T;
SESSION      : S E S S I O N;
SYSTEM       : S Y S T E M;
UR           : U R;
COMMIT       : C O M M I T;
ROLLBACK     : R O L L B A C K;
EXPLAIN      : E X P L A I N;
PLAN         : P L A N;
FOR          : F O R;
THROUGH      : T H R O U G H;

SEMI      : ';';
COMMA     : ',';
DOT       : '.';
LPAREN    : '(';
RPAREN    : ')';
LBRACE    : '{';
RBRACE    : '}';
STAR      : '*';
PLUS_PLUS : '++';
PLUS      : '+';
JSON_TEXT_ARROW : '->>';
JSON_ARROW : '->';
MINUS     : '-';
SLASH     : '/';
PERCENT   : '%';
NAMED_ARGUMENT_ARROW : '=>';
EQ        : '=';
NEQ       : '<>' | '!=' | '^=';
LTE       : '<=';
GTE       : '>=';
LT        : '<';
GT        : '>';
CONCAT    : '||';
AND_OP    : '&&';
NOT_OP    : '!';
SHIFT_LEFT : '<<';
SHIFT_RIGHT : '>>';
BIT_AND   : '&';
BIT_OR    : '|';
BIT_XOR   : '^';
BIT_NOT   : '~';
ASSIGN    : ':=';
DOUBLE_COLON : '::';
COLON     : ':';
JSON_CONTAINS : '@>';
AT        : '@';
QUESTION  : '?';
BACKTICK  : '`';

HEX_LITERAL
    : '0' [xX] [0-9A-Fa-f]+
    ;

HEX_STRING_LITERAL
    : X '\'' [0-9A-Fa-f]* '\''
    ;

NUMBER
    : DIGIT+ ({_input.LA(2) != '.'}? '.' DIGIT*)? ([eE] [+-]? DIGIT+)? [fFdD]?
    | '.' DIGIT+ ([eE] [+-]? DIGIT+)? [fFdD]?
    ;

STRING
    : (N | E | '_' [A-Za-z] [A-Za-z0-9_]*)? '\'' (~'\'' | '\'' '\'')* '\''
    | Q '\'' '[' ~[\]]* ']' '\''
    | Q '\'' '(' ~[)]* ')' '\''
    | Q '\'' '{' ~[}]* '}' '\''
    | Q '\'' '<' ~[>]* '>' '\''
    | Q '\'' '!' ~[!]* '!' '\''
    | Q '\'' '#' ~[#]* '#' '\''
    | Q '\'' '~' ~[~]* '~' '\''
    | Q '\'' '/' ~[/]* '/' '\''
    | Q '\'' '$' ~[$]* '$' '\''
    | Q '\'' '^' ~[^]* '^' '\''
    | Q '\'' '|' ~[|]* '|' '\''
    | Q '\'' ':' ~[:]* ':' '\''
    | Q '\'' ';' ~[;]* ';' '\''
    | Q '\'' '?' ~[?]* '?' '\''
    | Q '\'' '@' ~[@]* '@' '\''
    | Q '\'' '%' ~[%]* '%' '\''
    | Q '\'' '&' ~[&]* '&' '\''
    | Q '\'' '+' ~[+]* '+' '\''
    | Q '\'' '-' ~[-]* '-' '\''
    | Q '\'' '=' ~[=]* '=' '\''
    | Q '\'' ',' ~[,]* ',' '\''
    | Q '\'' '.' ~[.]* '.' '\''
    | Q '\'' '`' ~[`]* '`' '\''
    ;

DOUBLE_QUOTED_ID
    : '"' ('""' | ~'"')* '"'
    ;

BRACKET_QUOTED_ID
    : '[' ~[\]\r\n]* ']'
    ;

BIND_VARIABLE
    : ':' (ID | DIGIT+ | '"' ('""' | ~'"')* '"')
    ;

LOCAL_TEMP_ID
    : '#' [A-Za-z0-9_$\u0080-\uFFFF] [A-Za-z0-9_$#\u0080-\uFFFF]*
    ;

ID
    : [A-Za-z_\u0080-\uFFFF] [A-Za-z0-9_$#\u0080-\uFFFF]*
    ;

LINE_COMMENT
    : '--' ~[\r\n]* -> channel(COMMENTS)
    ;

C_LINE_COMMENT
    : '//' ~[\r\n]* -> channel(COMMENTS)
    ;

BLOCK_COMMENT
    : '/*' .*? '*/' -> channel(COMMENTS)
    ;

WS
    : [ \t\f\r\n]+ -> channel(HIDDEN)
    ;

fragment DIGIT : [0-9];
fragment A : [aA];
fragment B : [bB];
fragment C : [cC];
fragment D : [dD];
fragment E : [eE];
fragment F : [fF];
fragment G : [gG];
fragment H : [hH];
fragment I : [iI];
fragment J : [jJ];
fragment K : [kK];
fragment L : [lL];
fragment M : [mM];
fragment N : [nN];
fragment O : [oO];
fragment P : [pP];
fragment Q : [qQ];
fragment R : [rR];
fragment S : [sS];
fragment T : [tT];
fragment U : [uU];
fragment V : [vV];
fragment W : [wW];
fragment X : [xX];
fragment Y : [yY];
fragment Z : [zZ];
